{% set version = "1.3.3" %}

package:
  name: deap
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/deap/deap-{{ version }}.tar.gz
  sha256: 8772f1b0fff042d5e516b0aebac2c706243045aa7d0de8e0b8658f380181cf31
  patches:
    - 0000-no-2to3.patch  # [py>=35]

build:
  number: 0
  script:
    - 2to3 --output-dir={{ SRC_DIR }} -W -n {{ SRC_DIR }}  # [py>=35]
    - {{ PYTHON }} setup.py build_ext -I{{ PREFIX }}/include  # [unix]
    - {{ PYTHON }} setup.py build_ext -I"%LIBRARY_INC%"  # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]

  host:
    - numpy
    - pypandoc  # [not (osx and not x86_64)]
    - python
    - pip
  run:
    - numpy
    - python

test:
  requires:
    - nose  # [py<=39]
    - nose-cov  # [py<=39]
    - python
    - pip
  imports:
    - deap
    - deap.benchmarks
    - deap.tools
    - deap.tools._hypervolume
  commands:
    - python -m pip check
    - nosetests deap.tests --with-cov --cov deap  # [py<=39]

about:
  home: https://github.com/DEAP/deap
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Distributed Evolutionary Algorithms in Python
  doc_url: https://deap.readthedocs.io
  dev_url: https://github.com/deap/deap
  doc_source_url: https://github.com/DEAP/deap/tree/master/doc
  description: |
    DEAP is a novel evolutionary computation framework for rapid prototyping and testing of
    ideas. It seeks to make algorithms explicit and data structures transparent. It works
    in perfect harmony with parallelisation mechanism such as multiprocessing and SCOOP. The
    following documentation presents the key concepts and many features to build your own
    evolutions.

extra:
  recipe-maintainers:
    - bollwyvl
    - rhiever
    - tonyfast
