{% set version = "1.4.3" %}

package:
  name: deap
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/deap/deap-{{ version }}.tar.gz
  sha256: 7c97088fb05835bdc255bec475cb0e778de2b43e44cbefbf2bcd655aeec865fd

build:
  skip: true  # [py<37]
  number: 0
  script:
    - {{ PYTHON }} setup.py build_ext -I{{ PREFIX }}/include  # [unix]
    - {{ PYTHON }} setup.py build_ext -I"%LIBRARY_INC%"  # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]

  host:
    - numpy
    - pip
    - python
    - setuptools
  run:
    - numpy
    - python

test:
  source_files:
    - tests
  requires:
    - pytest-cov
    - pip
  imports:
    - deap
    - deap.benchmarks
    - deap.tools
    - deap.tools._hypervolume
  commands:
    - pip check
    - pytest -vv --cov=deap --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=37

about:
  home: https://github.com/DEAP/deap
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Distributed Evolutionary Algorithms in Python
  doc_url: https://deap.readthedocs.io
  dev_url: https://github.com/deap/deap
  doc_source_url: https://github.com/DEAP/deap/tree/{{ version }}/doc
  description: |
    DEAP is a novel evolutionary computation framework for rapid prototyping and testing of
    ideas. It seeks to make algorithms explicit and data structures transparent. It works
    in perfect harmony with parallelisation mechanism such as multiprocessing and SCOOP. The
    following documentation presents the key concepts and many features to build your own
    evolutions.

extra:
  recipe-maintainers:
    - bollwyvl
    - rhiever
    - tonyfast
