# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.4.4"
  python_check_max: "3.14"

package:
  name: deap
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/deap/deap-${{ version }}.tar.gz
  sha256: 50d4bd924fca5a16a3dba8bfdb1140a55e9c24ce50816ab4f5683d2f31c2d734

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - numpy
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python-moocore
    - numpy
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - deap
        - deap.benchmarks
        - deap.tools
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - files:
      source:
        - tests/
    requirements:
      run:
        - pytest-cov
        - python ${{ python_min }}.*
    script:
      - coverage run --source=deap --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=41

about:
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  summary: Distributed Evolutionary Algorithms in Python
  homepage: https://github.com/DEAP/deap
  repository: https://github.com/deap/deap
  documentation: https://deap.readthedocs.io
  description: |
    DEAP is a novel evolutionary computation framework for rapid prototyping and testing of
    ideas. It seeks to make algorithms explicit and data structures transparent. It works
    in perfect harmony with parallelisation mechanism such as multiprocessing and SCOOP. The
    following documentation presents the key concepts and many features to build your own
    evolutions.

extra:
  recipe-maintainers:
    - bollwyvl
    - rhiever
    - tonyfast
